### ISSUE TITLE
Is this "break" intentional?

### ISSUE THREAD

**Issue by ziacik** [pkohut/GeoFormulas#7]
https://github.com/pkohut/GeoFormulas/blob/8a8b3277d4fe0cd512c2cc0b29e3369f354aa3e3/GeoFormulas/GeodesicArcIntercept.cpp#L105

Previous algorithm was doing a loop with max of 10 iterations, now the `while` is still there, but it breaks after the first cycle. Is it intentional?

**Comment by pkohut** [comment]
As I recall, it is intentional, the test data for GAI did not pass otherwise.  
 
Main goal was to match the results of the data supplied by the FAA order.
https://github.com/pkohut/GeoFormulas/blob/master/8260.54ATestData/Application%20test%20Results.txt
